FROM php:5.6-fpm-alpine AS build

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions \
        bcmath \
        blackfire \
        gd \
        geoip \
        igbinary \
        imap \
        intl \
        mcrypt \
        memcache \
        memcached \
        mysql \
        opcache \
        pcntl \
        pdo_mysql \
        rdkafka \
        redis \
        soap \
        xmlrpc \
        zip

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN sed -i 's/;date.timezone =/date.timezone="Europe\/Brussels"/g' $PHP_INI_DIR/php.ini

FROM php:5.6-fpm-alpine AS final
COPY --from=build --chown=root:root /usr/local/lib/php/extensions/no-debug-non-zts-20131226/* /usr/local/lib/php/extensions/no-debug-non-zts-20131226/
COPY --from=build --chown=root:root /usr/local/etc/php/conf.d/* /usr/local/etc/php/conf.d/
COPY --from=build --chown=root:root /usr/lib/libXpm.so.4 /usr/lib/libXpm.so.4
COPY --from=build --chown=root:root /usr/lib/libpng16.so.16 /usr/lib/libpng16.so.16
COPY --from=build --chown=root:root /usr/lib/libjpeg.so.8 /usr/lib/libjpeg.so.8
COPY --from=build --chown=root:root /usr/lib/libvpx.so.4 /usr/lib/libvpx.so.4
COPY --from=build --chown=root:root /usr/lib/libfreetype.so.6 /usr/lib/libfreetype.so.6
COPY --from=build --chown=root:root /usr/lib/libX11.so.6 /usr/lib/libX11.so.6
COPY --from=build --chown=root:root /usr/lib/libbz2.so.1 /usr/lib/libbz2.so.1
COPY --from=build --chown=root:root /usr/lib/libxcb.so.1 /usr/lib/libxcb.so.1
COPY --from=build --chown=root:root /usr/lib/libXau.so.6 /usr/lib/libXau.so.6
COPY --from=build --chown=root:root /usr/lib/libXdmcp.so.6 /usr/lib/libXdmcp.so.6
COPY --from=build --chown=root:root /usr/lib/libbsd.so.0 /usr/lib/libbsd.so.0
COPY --from=build --chown=root:root /usr/lib/libGeoIP.so.1 /usr/lib/libGeoIP.so.1
COPY --from=build --chown=root:root /usr/lib/libc-client.so.1 /usr/lib/libc-client.so.1
COPY --from=build --chown=root:root /usr/lib/libicui18n.so.60 /usr/lib/libicui18n.so.60
COPY --from=build --chown=root:root /usr/lib/libicuuc.so.60 /usr/lib/libicuuc.so.60
COPY --from=build --chown=root:root /usr/lib/libicudata.so.60 /usr/lib/libicudata.so.60
COPY --from=build --chown=root:root /usr/lib/libgcc_s.so.1 /usr/lib/libgcc_s.so.1
COPY --from=build --chown=root:root /usr/lib/libicuio.so.60 /usr/lib/libicuio.so.60
COPY --from=build --chown=root:root /usr/lib/libmcrypt.so.4 /usr/lib/libmcrypt.so.4
COPY --from=build --chown=root:root /usr/lib/librdkafka.so.1 /usr/lib/librdkafka.so.1
COPY --from=build --chown=root:root /usr/lib/libzip.so.5 /usr/lib/libzip.so.5
COPY --from=build --chown=root:root /usr/lib/libmemcached.so.11 /usr/lib/libmemcached.so.11
COPY --from=build --chown=root:root /usr/lib/libsasl2.so.3 /usr/lib/libsasl2.so.3
COPY --from=build --chown=root:root /usr/lib/libstdc++.so.6 /usr/lib/libstdc++.so.6
