---
name: php-5.6
on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile-5.6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-5.6
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-docker:5.6
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/php-docker:buildcache-5.6
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/php-docker:buildcache-5.6,mode=max
